services:
  - type: web
    name: gautam-portfolio
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run main.py --server.port=$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13
    plan: free